import{a as v,i as a,S as E}from"./assets/vendor-D0cagnvz.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const q="47332202-20d723453e83dbf57917d8670";async function h(s,t=20,o){const i="https://pixabay.com/api/";try{return(await v.get(`${i}`,{params:{key:q,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:t}})).data}catch(e){a.error({title:"Error",message:`Error: ${e.message}`})}}function p(s){return s.map(({webformatURL:t,largeImageURL:o,tags:i,likes:e,views:r,comments:c,downloads:w})=>`
        <li class="img-card">
          <div class="img-img">
            <a class="gallery-link" href="${o}">
              <img class="gallery-image" src="${t}" alt="${i}" />
            </a>
          </div>
          <div class="img-info">
            <ul class="img-info-list">
              <li><h3>Likes</h3><p>${e}</p></li>
              <li><h3>Views</h3><p>${r}</p></li>
              <li><h3>Comments</h3><p>${c}</p></li>
              <li><h3>Downloads</h3><p>${w}</p></li>
            </ul>
          </div>
        </li>
      `).join("")}function y(s,t){s.insertAdjacentHTML("beforeend",t),d.classList.replace("hidden","load-more-button")}function g(s){s.innerHTML=""}a.settings({position:"topRight"});const S=document.querySelector(".js-search-form"),$=document.querySelector("#query"),n=document.getElementById("loader"),u=document.querySelector(".image-cards"),d=document.querySelector("#load-more");let m,l=1,f=100,L=300;d.addEventListener("click",M);const b=new E(".image-cards a");window.__formSubmitListenerAttached||(S.addEventListener("submit",s=>{if(s.preventDefault(),m=$.value.trim(),l=1,!m){a.warning({title:"Error",message:"Please enter a searched word"});return}n.classList.remove("disabled"),h(m,f,l).then(t=>{if(t.hits.length===0){a.warning({title:"No Results",message:"No images found for your query."}),g(u);return}g(u);const o=p(t.hits);if(y(u,o),Math.ceil(t.totalHits/f)<=l){d.classList.add("hidden"),n.classList.add("disabled"),a.warning({title:"No more pages",message:"We're sorry, but you've reached the end of search results."});return}d.classList.replace("hidden","load-more-button");let e=document.querySelector(".img-card");e&&(L=e.getBoundingClientRect().height*2),b.refresh()}).catch(t=>{console.error("Error fetching images:",t),a.error({title:"Error",message:`Failed to fetch images: ${t.message}`})}).finally(()=>{n.classList.add("disabled")})}),window.__formSubmitListenerAttached=!0);async function M(){l+=1;try{const s=await h(m,f,l);n.classList.remove("disabled"),console.log("Loader enabled"),await new Promise(i=>setTimeout(i,1500)),n.classList.add("disabled");let t=Math.ceil(s.totalHits/f);const o=p(s.hits);if(y(u,o),n.classList.add("disabled"),window.scrollBy({top:L,left:0,behavior:"smooth"}),l>=t){console.log("We're sorry, but you've reached the end of search results."),d.classList.add("hidden"),n.classList.add("disabled"),a.warning({title:"No more pages",message:"We're sorry, but you've reached the end of search results."});return}b.refresh()}catch{console.error("Error in onClickLoadMore:",error.message),a.error({title:"Error",message:`Failed to load more images: ${error.message}`})}}
//# sourceMappingURL=index.js.map
